import type { Course } from "./types"

export const courses: Course[] = [
  {
    id: "web-development-101",
    title: "Web Development Fundamentals",
    description: "Learn the core concepts of HTML, CSS, and JavaScript to build modern websites.",
    longDescription:
      "This comprehensive course covers everything you need to know to start building websites from scratch. You'll learn HTML for structure, CSS for styling, and JavaScript for interactivity. By the end of this course, you'll have the skills to create responsive, accessible, and interactive web pages.",
    thumbnail: "/placeholder.svg?height=225&width=400",
    price: 49.99,
    rating: 4.8,
    reviewCount: 342,
    enrolledCount: 1245,
    duration: "24 hours",
    level: "Beginner",
    featured: true,
    progress: 65,
    currentModule: 0,
    currentLesson: 2,
    learningOutcomes: [
      "Understand HTML document structure and semantic elements",
      "Create responsive layouts with CSS Flexbox and Grid",
      "Build interactive web pages with JavaScript",
      "Implement form validation and user input handling",
      "Deploy websites to production environments",
    ],
    modules: [
      {
        id: 0,
        title: "Introduction to HTML",
        lessons: [
          {
            title: "HTML Basics",
            type: "video",
            duration: "15 min",
            content: "Learn the fundamentals of HTML including document structure, elements, and attributes.",
            videoId: "qz0aGYrrlhU",
          },
          {
            title: "Semantic HTML",
            type: "video",
            duration: "12 min",
            content: "Understand how to use semantic HTML elements to improve accessibility and SEO.",
            videoId: "kGW8Al_cga4",
          },
          {
            title: "HTML Forms",
            type: "video",
            duration: "18 min",
            content: "Learn how to create interactive forms to collect user input.",
            videoId: "YwbIeMlxZAU",
          },
          {
            title: "HTML Quiz",
            type: "quiz",
            duration: "10 min",
            questions: [
              {
                question: "Which HTML element is used to define the main content of a document?",
                options: ["<content>", "<main>", "<section>", "<article>"],
                correctAnswer: "<main>",
              },
              {
                question: "Which attribute is used to specify the URL of an external resource?",
                options: ["href", "src", "link", "url"],
                correctAnswer: "src",
              },
              {
                question: "Which HTML element is used to create a dropdown list?",
                options: ["<input>", "<dropdown>", "<select>", "<option>"],
                correctAnswer: "<select>",
              },
            ],
          },
        ],
      },
      {
        id: 1,
        title: "CSS Styling",
        lessons: [
          {
            title: "CSS Selectors",
            type: "video",
            duration: "14 min",
            content: "Learn how to target HTML elements with different types of CSS selectors.",
            videoId: "l1mER1bV0N0",
          },
          {
            title: "CSS Box Model",
            type: "video",
            duration: "16 min",
            content: "Understand the CSS box model and how to control spacing and borders.",
            videoId: "rIO5326FgPE",
          },
          {
            title: "Flexbox Layout",
            type: "video",
            duration: "20 min",
            content: "Learn how to create flexible layouts with CSS Flexbox.",
            videoId: "JJSoEo8JSnc",
          },
        ],
      },
      {
        id: 2,
        title: "JavaScript Basics",
        lessons: [
          {
            title: "JavaScript Syntax",
            type: "video",
            duration: "18 min",
            content: "Learn the basic syntax, variables, and data types in JavaScript.",
            videoId: "W6NZfCO5SIk",
          },
          {
            title: "DOM Manipulation",
            type: "video",
            duration: "22 min",
            content: "Understand how to select and modify HTML elements with JavaScript.",
            videoId: "0ik6X4DJKCc",
          },
          {
            title: "Event Handling",
            type: "video",
            duration: "15 min",
            content: "Learn how to respond to user interactions with event listeners.",
            videoId: "e57ReoUn6kM",
          },
        ],
      },
    ],
  },
  {
    id: "react-masterclass",
    title: "React.js Masterclass",
    description: "Master React.js and build modern, interactive web applications.",
    longDescription:
      "This in-depth course will take you from React basics to advanced concepts. You'll learn component architecture, state management, hooks, context API, and how to integrate with backend services. By the end of this course, you'll be able to build complex, production-ready React applications.",
    thumbnail: "/placeholder.svg?height=225&width=400",
    price: 79.99,
    rating: 4.9,
    reviewCount: 512,
    enrolledCount: 2341,
    duration: "32 hours",
    level: "Intermediate",
    featured: true,
    progress: 25,
    currentModule: 0,
    currentLesson: 1,
    learningOutcomes: [
      "Build reusable functional and class components",
      "Manage application state effectively",
      "Implement routing with React Router",
      "Use hooks for state and side effects",
      "Connect React applications to APIs and backends",
    ],
    modules: [
      {
        id: 0,
        title: "React Fundamentals",
        lessons: [
          {
            title: "Introduction to React",
            type: "video",
            duration: "20 min",
            content: "Learn what React is and why it's popular for building user interfaces.",
            videoId: "Tn6-PIqc4UM",
          },
          {
            title: "Components and Props",
            type: "video",
            duration: "25 min",
            content: "Understand the component architecture and how to pass data with props.",
            videoId: "FdiUTOWM6uo",
          },
          {
            title: "State and Lifecycle",
            type: "video",
            duration: "22 min",
            content: "Learn how to manage component state and lifecycle methods.",
            videoId: "4ORZ1GmjaMc",
          },
        ],
      },
      {
        id: 1,
        title: "React Hooks",
        lessons: [
          {
            title: "useState Hook",
            type: "video",
            duration: "18 min",
            content: "Learn how to manage state in functional components with useState.",
            videoId: "O6P86uwfdR0",
          },
          {
            title: "useEffect Hook",
            type: "video",
            duration: "24 min",
            content: "Understand how to handle side effects in functional components.",
            videoId: "0ZJgIjIuY7U",
          },
          {
            title: "Custom Hooks",
            type: "video",
            duration: "20 min",
            content: "Learn how to create reusable logic with custom hooks.",
            videoId: "6ThXsUwLWvc",
          },
        ],
      },
    ],
  },
  {
    id: "python-data-science",
    title: "Python for Data Science",
    description: "Learn Python programming and essential libraries for data analysis and visualization.",
    longDescription:
      "This course teaches you Python from the ground up with a focus on data science applications. You'll learn how to use NumPy, Pandas, and Matplotlib to analyze and visualize data, and how to apply statistical methods to extract insights from datasets.",
    thumbnail: "/placeholder.svg?height=225&width=400",
    price: 69.99,
    rating: 4.7,
    reviewCount: 287,
    enrolledCount: 1876,
    duration: "28 hours",
    level: "Beginner",
    featured: true,
    progress: 100,
    currentModule: 2,
    currentLesson: 1,
    learningOutcomes: [
      "Write efficient Python code for data processing",
      "Manipulate and analyze data with Pandas",
      "Create insightful data visualizations",
      "Apply statistical methods to datasets",
      "Build predictive models with scikit-learn",
    ],
    modules: [
      {
        id: 0,
        title: "Python Basics",
        lessons: [
          {
            title: "Introduction to Python",
            type: "video",
            duration: "22 min",
            content: "Learn the basics of Python syntax, variables, and data types.",
            videoId: "kqtD5dpn9C8",
          },
          {
            title: "Control Flow",
            type: "video",
            duration: "18 min",
            content: "Understand conditionals, loops, and control structures in Python.",
            videoId: "Zp5MuPOtsSY",
          },
          {
            title: "Functions and Modules",
            type: "video",
            duration: "20 min",
            content: "Learn how to create reusable code with functions and modules.",
            videoId: "u-OmVr_fT4s",
          },
        ],
      },
      {
        id: 1,
        title: "Data Analysis with Pandas",
        lessons: [
          {
            title: "Introduction to Pandas",
            type: "video",
            duration: "25 min",
            content: "Learn the basics of the Pandas library for data manipulation.",
            videoId: "vmEHCJofslg",
          },
          {
            title: "Data Cleaning",
            type: "video",
            duration: "28 min",
            content: "Learn techniques for cleaning and preprocessing data.",
            videoId: "bDhvCp3_lYw",
          },
          {
            title: "Data Aggregation",
            type: "video",
            duration: "24 min",
            content: "Understand how to group and aggregate data for analysis.",
            videoId: "txMdrV1Ut64",
          },
        ],
      },
      {
        id: 2,
        title: "Data Visualization",
        lessons: [
          {
            title: "Matplotlib Basics",
            type: "video",
            duration: "20 min",
            content: "Learn how to create basic plots with Matplotlib.",
            videoId: "DAQNHzOcO5A",
          },
          {
            title: "Advanced Visualizations",
            type: "video",
            duration: "26 min",
            content: "Create complex and interactive visualizations for data analysis.",
            videoId: "0P7QnIQDBJY",
          },
          {
            title: "Dashboard Creation",
            type: "video",
            duration: "30 min",
            content: "Learn how to build interactive dashboards to present data.",
            videoId: "7G3lWlNvOMQ",
          },
        ],
      },
    ],
  },
  {
    id: "ux-design-principles",
    title: "UX Design Principles",
    description: "Learn the fundamentals of user experience design and create user-centered products.",
    thumbnail: "/placeholder.svg?height=225&width=400",
    price: 59.99,
    rating: 4.6,
    reviewCount: 198,
    enrolledCount: 876,
    duration: "20 hours",
    level: "Beginner",
    learningOutcomes: [
      "Understand user-centered design principles",
      "Conduct effective user research",
      "Create wireframes and prototypes",
      "Perform usability testing",
      "Design accessible interfaces",
    ],
    modules: [
      {
        id: 0,
        title: "Introduction to UX",
        lessons: [
          {
            title: "What is UX Design?",
            type: "video",
            duration: "15 min",
            content: "Learn the fundamentals of user experience design and its importance.",
            videoId: "SRec90j6lTY",
          },
          {
            title: "UX Design Process",
            type: "video",
            duration: "18 min",
            content: "Understand the different stages of the UX design process.",
            videoId: "v6n-4OLmZ1I",
          },
        ],
      },
      {
        id: 1,
        title: "User Research",
        lessons: [
          {
            title: "Research Methods",
            type: "video",
            duration: "22 min",
            content: "Learn different methods for gathering user insights.",
            videoId: "bAARmsXWDcs",
          },
          {
            title: "Creating User Personas",
            type: "video",
            duration: "20 min",
            content: "Learn how to create representative user personas for design.",
            videoId: "u44pBkvpxZc",
          },
        ],
      },
    ],
  },
  {
    id: "digital-marketing-essentials",
    title: "Digital Marketing Essentials",
    description: "Master the fundamentals of digital marketing strategies and tools.",
    thumbnail: "/placeholder.svg?height=225&width=400",
    price: 49.99,
    rating: 4.5,
    reviewCount: 156,
    enrolledCount: 723,
    duration: "18 hours",
    level: "Beginner",
    learningOutcomes: [
      "Develop effective digital marketing strategies",
      "Optimize content for search engines",
      "Create engaging social media campaigns",
      "Analyze marketing performance with analytics",
      "Implement email marketing campaigns",
    ],
    modules: [
      {
        id: 0,
        title: "Marketing Fundamentals",
        lessons: [
          {
            title: "Introduction to Digital Marketing",
            type: "video",
            duration: "20 min",
            content: "Learn the basics of digital marketing and its channels.",
            videoId: "nU-IIXBWlS4",
          },
          {
            title: "Creating a Marketing Strategy",
            type: "video",
            duration: "25 min",
            content: "Learn how to develop a comprehensive digital marketing strategy.",
            videoId: "q4IDC1Aa4uQ",
          },
        ],
      },
      {
        id: 1,
        title: "SEO and Content Marketing",
        lessons: [
          {
            title: "SEO Basics",
            type: "video",
            duration: "22 min",
            content: "Learn the fundamentals of search engine optimization.",
            videoId: "DvwS7cV9GmQ",
          },
          {
            title: "Content Marketing Strategies",
            type: "video",
            duration: "18 min",
            content: "Understand how to create valuable content that attracts and engages audiences.",
            videoId: "RywSS0sArI0",
          },
        ],
      },
    ],
  },
]

export const enrolledCourses = ["web-development-101", "react-masterclass", "python-data-science"]
